#! /bin/bash

kill $(pidof mosquitto_sub)

mosquitto_sub -h lubuntuN7 -p 1883 -i 'mqtt_sub_vap.power' -t vaponic/tele/SENSOR >> data/vaponicData.$(date +%b%d).log &

./import.py -d "$(date -d 'yesterday' '+%b%d')" &
