#! /usr/bin/env python3

import sys
import argparse

parser = argparse.ArgumentParser(description='Push data to database from local file.')

parser.add_argument('-d', '--datafile', type=str, nargs='+', help='name of the datafile')

parser.add_argument('-v', '--verbose', action='count', default=0, help='verbose mode')
        
args = parser.parse_args()

print(args)
print(args.verbose)
print(type(args.verbose))
print(args.datafile)
print(type(args.datafile))

#try:
#    thisday = sys.argv[1]
#    print (thisday)
#except:
#    sys.exit("1 argument expected (date), none received")

def main(syncday="missing date argument", log=sys.stdout):
    if syncday=="missing date argument":
        log.write("hello\n")
        sys.exit("Error: "+syncday+". No data was pushed.")
    
    print("data/vaponicData."+syncday+".log")

#main(thisday)
#main()

